name: Deploy to Server

on:
  workflow_dispatch:

jobs:
  prepare-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          sudo apt update
          sudo apt install -y nginx python3-venv python3-pip python3-certbot-nginx git certbot
          sudo reboot

  deploy:
    runs-on: ubuntu-latest
    needs: prepare-server
    steps:
    - name: Wait for server to come back online
      run: |
        for i in {1..30}; do
          if ssh -o StrictHostKeyChecking=no -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "echo 'Server is back online'"; then
            break
          fi
          echo "Waiting for server to come back online..."
          sleep 10
        done

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Define variables
          APP_DIR="/var/www/baidakovru"
          DEPLOY_SCRIPT="$APP_DIR/deploy.sh"
          REPO_URL="https://github.com/baidakovil/baidakovru.git"
          LOG_FILE="/tmp/deploy.log"

          # Redirect all output to the log file
          exec > >(tee -a $LOG_FILE) 2>&1

          # Check if deploy.sh exists, if not, clone the repository
          if [ ! -d "$APP_DIR" ]; then
            echo "App dir was not found. Creating folder..."
            sudo mkdir -p $APP_DIR || { echo "Failed to create app directory"; exit 1; }
            sudo chown -R www-data:www-data $APP_DIR || { echo "Failed to change ownership"; exit 1; }
            sudo chmod -R 2775 $APP_DIR || { echo "Failed to change permissions"; exit 1; }
            sudo git config --global --add safe.directory $APP_DIR || { echo "Failed to add APP_DIR to git safe dir"; exit 1; }
            sudo -u www-data git clone $REPO_URL $APP_DIR || { echo "Failed to clone repository"; exit 1; }
          fi
                    
          # Run deploy.sh script after ensuring it exists and is executable
          if [ -f "$DEPLOY_SCRIPT" ]; then
            sudo chmod +x $DEPLOY_SCRIPT
            ENV_FILE='${{ secrets.ENV_FILE }}' bash $DEPLOY_SCRIPT
          else
            echo "Error: deploy.sh not found after attempted clone. Deployment failed."
            exit 1
          fi