name: Deploy to Server

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        envs: ENV_FILE
        script: |
          # Define variables
          APP_DIR="/var/www/baidakovru"
          DEPLOY_SCRIPT="$APP_DIR/deploy.sh"
          REPO_URL="https://github.com/baidakovil/baidakovru.git"

          # Check if deploy.sh exists, if not, clone the repository
          if [ ! -d "$APP_DIR" ]; then
            echo "App dir was not found. Creating folder..."
            sudo mkdir -p $APP_DIR
            sudo chown www-data:www-data $APP_DIR
            sudo chmod 755 $APP_DIR
            echo "Cloning repository"
            sudo -u www-data git clone $REPO_URL $APP_DIR
          fi
          
          # Run deploy.sh script after ensurin it is exist and executable
          if [ -f "$DEPLOY_SCRIPT" ]; then
            sudo chmod +x $DEPLOY_SCRIPT
            ENV_FILE='${{ secrets.ENV_FILE }}' bash $DEPLOY_SCRIPT
          else
            echo "Error: deploy.sh not found after attempted clone. Deployment failed."
            exit 1
          fi